# Dockerfile for Anvil (L2)
FROM ghcr.io/foundry-rs/foundry:latest

WORKDIR /app

# Expose Anvil port
EXPOSE 9545

# Inicio de Anvil
ENTRYPOINT ["anvil", "-p", "9545", "--chain-id", "1338", "--host", "0.0.0.0"]
